In [44]:
import pandas as pd
import numpy as np
import pickle

In [2]:
total_crop_dataset = pd.read_csv('../crop_production.csv')

In [3]:
uttar_pradesh = total_crop_dataset[total_crop_dataset['State_Name']=='Uttar Pradesh']

In [4]:
uttar_pradesh.head()

State_Name District_Name  Crop_Year       Season       Crop  \
198276  Uttar Pradesh          AGRA       1997  Kharif       Arhar/Tur   
198277  Uttar Pradesh          AGRA       1997  Kharif           Bajra   
198278  Uttar Pradesh          AGRA       1997  Kharif       Groundnut   
198279  Uttar Pradesh          AGRA       1997  Kharif           Jowar   
198280  Uttar Pradesh          AGRA       1997  Kharif           Maize   

           Area  Production  
198276   6538.0      9664.0  
198277  99898.0    147994.0  
198278     27.0        22.0  
198279    725.0       406.0  
198280    138.0       316.0

In [5]:
uttar_pradesh.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33306 entries, 198276 to 231581
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   State_Name     33306 non-null  object 
 1   District_Name  33306 non-null  object 
 2   Crop_Year      33306 non-null  int64  
 3   Season         33306 non-null  object 
 4   Crop           33306 non-null  object 
 5   Area           33306 non-null  float64
 6   Production     33189 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 2.0+ MB


In [6]:
uttar_pradesh.isnull().sum()

State_Name         0
District_Name      0
Crop_Year          0
Season             0
Crop               0
Area               0
Production       117
dtype: int64

In [7]:
uttar_pradesh = uttar_pradesh.dropna()

In [8]:
uttar_pradesh.isnull().sum()

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

In [9]:
uttar_pradesh['District_Name'].unique()

array(['AGRA', 'ALIGARH', 'ALLAHABAD', 'AMBEDKAR NAGAR', 'AMETHI',
       'AMROHA', 'AURAIYA', 'AZAMGARH', 'BAGHPAT', 'BAHRAICH', 'BALLIA',
       'BALRAMPUR', 'BANDA', 'BARABANKI', 'BAREILLY', 'BASTI', 'BIJNOR',
       'BUDAUN', 'BULANDSHAHR', 'CHANDAULI', 'CHITRAKOOT', 'DEORIA',
       'ETAH', 'ETAWAH', 'FAIZABAD', 'FARRUKHABAD', 'FATEHPUR',
       'FIROZABAD', 'GAUTAM BUDDHA NAGAR', 'GHAZIABAD', 'GHAZIPUR',
       'GONDA', 'GORAKHPUR', 'HAMIRPUR', 'HAPUR', 'HARDOI', 'HATHRAS',
       'JALAUN', 'JAUNPUR', 'JHANSI', 'KANNAUJ', 'KANPUR DEHAT',
       'KANPUR NAGAR', 'KASGANJ', 'KAUSHAMBI', 'KHERI', 'KUSHI NAGAR',
       'LALITPUR', 'LUCKNOW', 'MAHARAJGANJ', 'MAHOBA', 'MAINPURI',
       'MATHURA', 'MAU', 'MEERUT', 'MIRZAPUR', 'MORADABAD',
       'MUZAFFARNAGAR', 'PILIBHIT', 'PRATAPGARH', 'RAE BARELI', 'RAMPUR',
       'SAHARANPUR', 'SAMBHAL', 'SANT KABEER NAGAR', 'SANT RAVIDAS NAGAR',
       'SHAHJAHANPUR', 'SHAMLI', 'SHRAVASTI', 'SIDDHARTH NAGAR',
       'SITAPUR', 'SONBHADRA', 'SULTAN

In [10]:
uttar_pradesh['District_Name'].nunique()

75

In [11]:
uttar_pradesh_filtered = uttar_pradesh[
    (uttar_pradesh['Crop']=='Wheat') | 
    (uttar_pradesh['Crop']=='Rice')  |
    (uttar_pradesh['Crop']=='Jowar')  |
    (uttar_pradesh['Crop']=='Bajra')  |
    (uttar_pradesh['Crop']=='Cardamom')  |
    (uttar_pradesh['Crop']=='Garlic')  |
    (uttar_pradesh['Crop']=='Turmeric')  |
    (uttar_pradesh['Crop']=='Ginger')  |
    (uttar_pradesh['Crop']=='Cotton(lint)')  |
    (uttar_pradesh['Crop']=='Linseed')  |
    (uttar_pradesh['Crop']=='Sesamum')  |
    (uttar_pradesh['Crop']=='Coconut ')  |
    (uttar_pradesh['Crop']=='Onion')  |
    (uttar_pradesh['Crop']=='Arhar/Tur')  |
    (uttar_pradesh['Crop']=='Potato')  |
    (uttar_pradesh['Crop']=='Maize')  
]

In [12]:
uttar_pradesh_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15047 entries, 198276 to 231580
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   State_Name     15047 non-null  object 
 1   District_Name  15047 non-null  object 
 2   Crop_Year      15047 non-null  int64  
 3   Season         15047 non-null  object 
 4   Crop           15047 non-null  object 
 5   Area           15047 non-null  float64
 6   Production     15047 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 940.4+ KB


In [13]:
uttar_pradesh['Season'].unique()

array(['Kharif     ', 'Rabi       ', 'Summer     ', 'Whole Year '],
      dtype=object)

In [14]:
uttar_pradesh_filtered['Crop'].nunique()

14

In [15]:
uttar_pradesh_filtered_ohe = pd.get_dummies(uttar_pradesh_filtered, columns=['District_Name', 'Season','Crop'],drop_first=True)

In [16]:
uttar_pradesh_filtered_ohe.head()

State_Name  Crop_Year     Area  Production  District_Name_ALIGARH  \
198276  Uttar Pradesh       1997   6538.0      9664.0                      0   
198277  Uttar Pradesh       1997  99898.0    147994.0                      0   
198279  Uttar Pradesh       1997    725.0       406.0                      0   
198280  Uttar Pradesh       1997    138.0       316.0                      0   
198284  Uttar Pradesh       1997    110.0      1088.0                      0   

        District_Name_ALLAHABAD  District_Name_AMBEDKAR NAGAR  \
198276                        0                             0   
198277                        0                             0   
198279                        0                             0   
198280                        0                             0   
198284                        0                             0   

        District_Name_AMETHI  District_Name_AMROHA  District_Name_AURAIYA  \
198276                     0                     0                      0   
198277                     0                     0                      0   
198279                     0                     0                      0   
198280                     0                     0                      0   
198284                     0                     0                      0   

        ...  Crop_Ginger  Crop_Jowar  Crop_Linseed  Crop_Maize  Crop_Onion  \
198276  ...            0           0             0           0           0   
198277  ...            0           0             0           0           0   
198279  ...            0           1             0           0           0   
198280  ...            0           0             0           1           0   
198284  ...            0           0             0           0           1   

        Crop_Potato  Crop_Rice  Crop_Sesamum  Crop_Turmeric  Crop_Wheat  
198276            0          0             0              0           0  
198277            0          0             0              0           0  
198279            0          0             0              0           0  
198280            0          0             0              0           0  
198284            0          0             0              0           0  

[5 rows x 94 columns]

In [47]:
uttar_pradesh_filtered_ohe[(uttar_pradesh_filtered['Area']==123600.)].transpose()

198296
State_Name             Uttar Pradesh
Crop_Year                       1997
Area                          123600
Production                    391030
District_Name_ALIGARH              0
...                              ...
Crop_Potato                        0
Crop_Rice                          0
Crop_Sesamum                       0
Crop_Turmeric                      0
Crop_Wheat                         1

[94 rows x 1 columns]

In [17]:
uttar_pradesh_filtered_ohe.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15047 entries, 198276 to 231580
Data columns (total 94 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   State_Name                         15047 non-null  object 
 1   Crop_Year                          15047 non-null  int64  
 2   Area                               15047 non-null  float64
 3   Production                         15047 non-null  float64
 4   District_Name_ALIGARH              15047 non-null  uint8  
 5   District_Name_ALLAHABAD            15047 non-null  uint8  
 6   District_Name_AMBEDKAR NAGAR       15047 non-null  uint8  
 7   District_Name_AMETHI               15047 non-null  uint8  
 8   District_Name_AMROHA               15047 non-null  uint8  
 9   District_Name_AURAIYA              15047 non-null  uint8  
 10  District_Name_AZAMGARH             15047 non-null  uint8  
 11  District_Name_BAGHPAT              15047 non-nul

In [43]:
uttar_pradesh_filtered_ohe.columns

Index(['State_Name', 'Crop_Year', 'Area', 'Production',
       'District_Name_ALIGARH', 'District_Name_ALLAHABAD',
       'District_Name_AMBEDKAR NAGAR', 'District_Name_AMETHI',
       'District_Name_AMROHA', 'District_Name_AURAIYA',
       'District_Name_AZAMGARH', 'District_Name_BAGHPAT',
       'District_Name_BAHRAICH', 'District_Name_BALLIA',
       'District_Name_BALRAMPUR', 'District_Name_BANDA',
       'District_Name_BARABANKI', 'District_Name_BAREILLY',
       'District_Name_BASTI', 'District_Name_BIJNOR', 'District_Name_BUDAUN',
       'District_Name_BULANDSHAHR', 'District_Name_CHANDAULI',
       'District_Name_CHITRAKOOT', 'District_Name_DEORIA',
       'District_Name_ETAH', 'District_Name_ETAWAH', 'District_Name_FAIZABAD',
       'District_Name_FARRUKHABAD', 'District_Name_FATEHPUR',
       'District_Name_FIROZABAD', 'District_Name_GAUTAM BUDDHA NAGAR',
       'District_Name_GHAZIABAD', 'District_Name_GHAZIPUR',
       'District_Name_GONDA', 'District_Name_GORAKHPUR',
     

In [18]:
uttar_pradesh_filtered_ohe.isnull().sum()

State_Name               0
Crop_Year                0
Area                     0
Production               0
District_Name_ALIGARH    0
                        ..
Crop_Potato              0
Crop_Rice                0
Crop_Sesamum             0
Crop_Turmeric            0
Crop_Wheat               0
Length: 94, dtype: int64

In [19]:
X = uttar_pradesh_filtered_ohe.drop(['State_Name','Crop_Year','Production'],axis=1).values

In [20]:
y = uttar_pradesh_filtered_ohe.iloc[:,3].values

In [21]:
y

array([9.66400e+03, 1.47994e+05, 4.06000e+02, ..., 1.27010e+05,
       1.05000e+02, 2.38200e+03])

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [24]:
from sklearn.linear_model import LinearRegression,Lasso
linear_regression = LinearRegression()
lasso = Lasso()

In [25]:
linear_regression.fit(X_train,y_train)
lasso.fit(X_train,y_train)

Lasso()

In [26]:
from sklearn.ensemble import RandomForestRegressor
rfregressor = RandomForestRegressor()

In [27]:
rfregressor.fit(X_train,y_train)

RandomForestRegressor()

In [28]:
y_pred = rfregressor.predict(X_test)

In [29]:
from sklearn.metrics import r2_score

In [30]:
r2_score(y_test,y_pred)

0.9738793889572542

In [31]:
accuracy = rfregressor.score(X_test,y_test)
print(accuracy*100,'%')

97.38793889572543 %


In [32]:
accuracy = linear_regression.score(X_test,y_test)
print(accuracy*100,'%')

77.46103682481265 %


In [33]:
accuracy = lasso.score(X_test,y_test)
print(accuracy*100,'%')

77.45442433645091 %


In [45]:
filename = 'Uttar_Pradesh_Model.sav'
pickle.dump(rfregressor, open(filename, 'wb'))
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, y_test)
result

0.9738793889572542

In [34]:
from sklearn.model_selection import cross_val_score

In [35]:
cross_val_score(RandomForestRegressor(),X,y,cv=5)

array([0.94004201, 0.95315661, 0.95236971, 0.94296441, 0.94938007])

In [36]:
cross_val_score(LinearRegression(),X,y,cv=5)

array([ 7.26150689e-01, -3.03119359e+14, -4.84651720e+11,  5.70353795e-01,
        5.20213113e-01])

In [37]:
cross_val_score(Lasso(alpha=200,max_iter=10000),X,y,cv=5)

array([0.7239794 , 0.69898667, 0.72910063, 0.88370401, 0.89841164])

In [38]:
from sklearn.model_selection import GridSearchCV

In [39]:
model_params = {
    'lasso':{
        'model':Lasso(),
        'params':{
            'alpha':[1,10,20,30,200],
            'max_iter':[10000]
        }
    }
}

In [40]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(X,y)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

In [41]:
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                        best_params
0  lasso    0.786836  {'alpha': 200, 'max_iter': 10000}